### ISSUE TITLE
Installing on a brand new setup - getting errors in HA log

### ISSUE THREAD

**Issue by darwinsfoot** [djtimca/hagooglewifi#26]
Apologies if I don't get basic domain lingo - it's only a couple of hours since my very first install of Home Assistant.

After having added the Google Wifi package, I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/googlewifi/sensor.py", line 32, in async_setup_entry
    for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

It's the same error for all of these:
![image](https://user-images.githubusercontent.com/26108321/106335097-64bd4080-628c-11eb-9b48-4cec88e5b2f6.png)

Any suggestions?

**Comment by djtimca** [comment]
Uninstall the integration, get a new API key and reinstall. Restart Home Assistant and then leave it for a while. I had issues last night but after following that about 12 hours later everything came back up. Seems to be something with the Google API

**Comment by darwinsfoot** [comment]
Got the same error in the log upon clean re-install - will let it sit and try to restart/follow up a couple of times over the coming days.

**Comment by darwinsfoot** [comment]
Still getting the ssme error when reloading the integration. Any ideas?

**Comment by djtimca** [comment]
Unfortunately I couldn't get any additional information on my system when it did this and can't replicate it to try to get more logging from the back end API where there might be more to go on. 

If it happens again to me I will try to dig a little deeper.

**Comment by snozzley** [comment]
Having the same problem here too.  
Do we need to do anything specific with the google account that we create the token with? Does it need any specific permissions within google home/wifi apps?

**Comment by snozzley** [comment]
Yeah seems to be a google api permission/setup problem.
Running some of the API calls through postman fails with a 403 (permission denied) and this message:
` "code": 403,
        "message": "Home Foyer API has not been used in project 936475......before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/googlehomefoyer-pa.googleapis.com/overview?project=936475...... then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
        "status": "PERMISSION_DENIED",
        "details": [
            {
                "@type": "type.googleapis.com/google.rpc.Help",
                "links": [
                    {
                        "description": "Google developers console API activation",
                        "url": "https://console.developers.google.com/apis/api/googlehomefoyer-pa.googleapis.com/overview?project=936475......"
                    }
                ]
            },
            {
                "@type": "type.googleapis.com/google.rpc.ErrorInfo",
                "reason": "SERVICE_DISABLED",
                "domain": "googleapis.com",
                "metadata": {
                    "consumer": "projects/936475......",
                    "service": "googlehomefoyer-pa.googleapis.com"
                }
            }
        ]`
I've redacted half the project number in case that's meant to be private?

Following the link it provided, I just get a page with the following:

> You do not have sufficient permissions to view this page

There was an error while loading /apis/api/googlehomefoyer-pa.googleapis.com/overview?project=google.com:api-project-936475......&pli=1.
You are missing at least one of the following required permissions:

Project

resourcemanager.projects.get
serviceusage.services.get

Check that the project ID is valid and that you have permissions to access it.

>
At which point I get a bit stuck.. but yeah seems like we need to configure something in google api's for this to work?

**Comment by djtimca** [comment]
Sorry for long time to reply - I have seen this where the user you are connecting with is not the "owner" of the Google Wifi system (although this doesn't always work). Unfortunately to change the owner you have to completely reset your Google Wifi network and build it from scratch.

**Comment by ryanmsnyder** [comment]
Getting the same error. Installed via HACS initially. Uninstalled and added the integration manually to custom_components and also got a new refresh token through the Chrome plugin. Still getting the same error. Also, I'm the owner of the Google WiFi system. Any suggestions? Thanks for the integration. Excited to get it working.

```
2022-07-23 19:09:01 INFO (MainThread) [homeassistant.setup] Setting up googlewifi
2022-07-23 19:09:01 INFO (MainThread) [homeassistant.setup] Setup of domain googlewifi took 0.0 seconds
2022-07-23 19:09:13 INFO (MainThread) [custom_components.googlewifi] Setting up platform: binary_sensor
2022-07-23 19:09:13 INFO (MainThread) [custom_components.googlewifi] Setting up platform: device_tracker
2022-07-23 19:09:13 INFO (MainThread) [custom_components.googlewifi] Setting up platform: switch
2022-07-23 19:09:13 INFO (MainThread) [custom_components.googlewifi] Setting up platform: light
2022-07-23 19:09:13 INFO (MainThread) [custom_components.googlewifi] Setting up platform: sensor
2022-07-23 19:09:13 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.googlewifi
2022-07-23 19:09:13 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.googlewifi
2022-07-23 19:09:13 INFO (MainThread) [homeassistant.components.switch] Setting up switch.googlewifi
2022-07-23 19:09:13 INFO (MainThread) [homeassistant.components.light] Setting up light.googlewifi
2022-07-23 19:09:13 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.googlewifi
2022-07-23 19:09:13 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up googlewifi platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/binary_sensor.py", line 29, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-07-23 19:09:13 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up googlewifi platform for device_tracker
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/device_tracker.py", line 31, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-07-23 19:09:13 ERROR (MainThread) [homeassistant.components.switch] Error while setting up googlewifi platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/switch.py", line 45, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-07-23 19:09:13 ERROR (MainThread) [homeassistant.components.light] Error while setting up googlewifi platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/light.py", line 30, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-07-23 19:09:13 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up googlewifi platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/sensor.py", line 32, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
```
