### ISSUE TITLE
Entities go offline (unknown state) often 

### ISSUE THREAD

**Issue by ee02217** [djtimca/hagooglewifi#3]
Version: 0.0.8
Entities often go to unknown state and recover automatically.
![image](https://user-images.githubusercontent.com/60232595/98224566-863bb400-1f4b-11eb-902a-e5618ba9f36d.png)

Error trace:

``
Logger: custom_components.googlewifi
Source: custom_components/googlewifi/__init__.py:126
Integration: Google WiFi (documentation)
First occurred: 4 November 2020, 22:17:44 (27 occurrences)
Last logged: 9:01:27

Unexpected error fetching GoogleWifi data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 217, in structure_systems
    for this_device in devices_list["stations"]:
KeyError: 'stations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/googlewifi/__init__.py", line 121, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 142, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 229, in structure_systems
    raise GoogleWifiException(error)
googlewifi.GoogleWifiException: 'stations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 126, in _async_update_data
    raise PlatformNotReady from error
homeassistant.exceptions.PlatformNotReady
``

**Comment by djtimca** [comment]
Should be fixed in latest release. Please reopen if it is still occurring - will monitor on my system as well.

**Comment by djtimca** [comment]
The fix in 0.0.9 did not work, but version 0.1.0 seems to have solved this problem for good.
