### ISSUE TITLE
Two networks across different houses problem

### ISSUE THREAD

**Issue by bellringer2** [djtimca/hagooglewifi#37]
I have two networks across two houses. Several sensors are coming up “unknown”. 
connected devices
Download speed  and traffic *
Upload speed and traffic *
Guest devices
the ones marked with * show data for the network that my HA instance is on but “unknown” for the other sensors. The sensors without * show data for my other network but unknown on the sensors marked with *. Very strange!!  Any help would be greatly appreciated. 
also getting errors in log attached

Logger: homeassistant.components.sensor
Source: custom_components/googlewifi/sensor.py:264 
Integration: Sensor (documentation, issues) 
First occurred: 25 May 2021, 21:19:06 (2 occurrences) 
Last logged: 25 May 2021, 21:19:06

Error adding entities for domain sensor with platform googlewifi
Error while setting up googlewifi platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
    state = self.state
  File "/config/custom_components/googlewifi/sensor.py", line 264, in state
    self._state = self.coordinator.data[self._system_id][
KeyError: 'connected_devices'

Also

This error originated from a custom integration.

Logger: custom_components.googlewifi
Source: custom_components/googlewifi/__init__.py:171 
Integration: Google WiFi (documentation, issues) 
First occurred: 8:52:49 (6 occurrences) 
Last logged: 13:49:20

Unexpected error fetching GoogleWifi data: 'operationState'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 180, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 284, in structure_systems
    sensitive_info = await self.get_sensitive_info(system_id=this_system["id"], station_ids=station_ids)
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 616, in get_sensitive_info
    status = status["operationState"]
KeyError: 'operationState'

**Comment by djtimca** [comment]
I think there are still some open issues on the speed sensors. Will try to address in a future version.

**Comment by djtimca** [comment]
Try the latest - I think most of this should be cleared up now.
