### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by gmlupatelli** [djtimca/hagooglewifi#42]
System:
HassIO is running on a Raspberry PI 4 with 4Gb of RAM

**Core**
  Version
  core-2021.8.8
  Newest Version
  core-2021.8.8

**Supervisor**
  Version
  supervisor-2021.08.1
  Newest Version
  supervisor-2021.08.1

**Host**
  Operating System
  Home Assistant OS 6.2
  Deployment
  production

**Log info:**
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/googlewifi/switch.py:210
Integration: Google WiFi Integration (documentation, issues)
First occurred: September 1, 2021, 9:54:55 PM (1176 occurrences)
Last logged: 11:24:20 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/config/custom_components/googlewifi/__init__.py", line 308, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in _stringify_state
    if not self.available:
  File "/config/custom_components/googlewifi/switch.py", line 210, in available
    self.coordinator.data[self._system_id]["devices"][self._item_id].get(
KeyError: 'B15F4BC3FC43157370628CDD396AE15274EC48F6DF60BCB9CD5C1B9A4E727C30'
```

**When this happen**
I couldn't pinpoint what triggers this error. It starts just after restarting the HA and keeps repeting.

**Comment by djtimca** [comment]
I have seen this when a device has disappeared from the Google Wifi history, but is still registered as a device in HA. You can remove and reinstall the integration to get a clean device list, but it may change some of the names so fair warning you may have some automation and Lovelace work to do once you do that.
