### ISSUE TITLE
Google wifi intergration error

### ISSUE THREAD

**Issue by danfrancis1988** [djtimca/hagooglewifi#65]
Hi I was wondering if anyone could help me I keep having the error with Google wifi intergration, I have uninstalled a couple of times, along with restarting and using different token. I'm probably doing something wrong. below is the error log.

2022-03-30 17:34:56 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up googlewifi platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/binary_sensor.py", line 29, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-03-30 17:34:56 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up googlewifi platform for device_tracker
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/device_tracker.py", line 31, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-03-30 17:34:56 ERROR (MainThread) [homeassistant.components.switch] Error while setting up googlewifi platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/switch.py", line 45, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-03-30 17:34:56 ERROR (MainThread) [homeassistant.components.light] Error while setting up googlewifi platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/light.py", line 30, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
2022-03-30 17:34:56 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up googlewifi platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/googlewifi/sensor.py", line 32, in async_setup_entry
for system_id, system in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by djtimca** [comment]
Try again with the latest release 0.1.31
