### ISSUE TITLE
Device_trackers picked by integration all show as Unavailable

### ISSUE THREAD

**Issue by deeteeakl** [djtimca/hagooglewifi#79]
I have tried de-installing and re-installing a couple of time but the issue remains.  I have attached the log file entry relating to the integration and its showing "Session closed", not sure if that might related.  I installed this integration to try and track whether certain devices were connected to the wifi or not.. I could have sworn this worked a day or two ago.  

This error originated from a custom integration.

Logger: custom_components.googlewifi
Source: custom_components/googlewifi/__init__.py:171
Integration: Google WiFi (documentation, issues)
First occurred: 23 August 2022 at 20:44:59 (3122 occurrences)
Last logged: 22:48:47

Unexpected error fetching GoogleWifi data: Session is closed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.10/site-packages/googlewifi/__init__.py", line 188, in get_systems
    response = await self.get_api(url, headers, payload)
  File "/usr/local/lib/python3.10/site-packages/googlewifi/__init__.py", line 63, in get_api
    async with self._session.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by deeteeakl** [comment]
I just rebooted the server HA is on and the integration is working again.  Not seeing any errors in the log either for now.
