### ISSUE TITLE
Error with last update

### ISSUE THREAD

**Issue by marc3k18** [djtimca/hagooglewifi#88]
Logger: homeassistant.loader
Source: custom_components/googlewifi/__init__.py:8
Integration: Google WiFi Integration ([documentation](https://github.com/djtimca/hagooglewifi), [issues](https://github.com/djtimca/hagooglewifi/issues))
First occurred: 11:51:11 PM (1 occurrences)
Last logged: 11:51:11 PM

Unexpected exception importing component custom_components.googlewifi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 730, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/googlewifi/__init__.py", line 8, in <module>
    from googlewifi import GoogleHomeIgnoreDevice, GoogleWifi, GoogleWifiException
  File "/usr/local/lib/python3.10/site-packages/googlewifi/__init__.py", line 8, in <module>
    from ghome_foyer_api.api_pb2 import GetHomeGraphRequest
  File "/usr/local/lib/python3.10/site-packages/ghome_foyer_api/api_pb2.py", line 18, in <module>
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor_pool.py", line 220, in AddSerializedFile
    file_desc = self._ConvertFileProtoToFileDescriptor(file_desc_proto)
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor_pool.py", line 771, in _ConvertFileProtoToFileDescriptor
    message_desc = self._ConvertMessageDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor_pool.py", line 913, in _ConvertMessageDescriptor
    self._CheckConflictRegister(desc, desc.full_name, desc.file.name)
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor_pool.py", line 192, in _CheckConflictRegister
    raise TypeError(error_msg)
TypeError: Conflict register for file "ghome_foyer_api/api.proto": google.internal.home.foyer.v1.GetAssistantRoutinesRequest is already defined in file "google/internal/home/foyer/v1.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication.

**Comment by DerekF35** [comment]
Are you using Google Home HACS integration?  If so, updating to the newly release v1.9.17 will allow them to play nice together.  I had your error as well and can confirm Google Home v1.9.17 fixed it for me.

**Comment by frakman1** [comment]
I have this error too and I also have the Google Home HACS Integration.
I tried to update Google Home Integration but there is no option to Update within HACS:

<img width="553" alt="image" src="https://github.com/djtimca/hagooglewifi/assets/5826484/f6223783-3fb5-4758-8e34-440a7cb85513">


 It shows the current version as 1.9.15 and the latest version is 1.10.0 so I'm not sure why it doesn't see it:

<img width="234" alt="image" src="https://github.com/djtimca/hagooglewifi/assets/5826484/ac4cd070-d058-4822-ae5a-eda746b4a958">


I am using Home Assistant Core in docker within UNRAID. Obtained from: https://registry.hub.docker.com/r/homeassistant/home-assistant/

Home Assistant 2022.12.6
Frontend 20221213.0 - latest
