### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by frakman1** [djtimca/hagooglewifi#95]
Using the latest Home Assistant Core: Home Assistant 2023.7.2.  Frontend 20230705.1 - latest
Latest HA-GoogleWiFi from HACS: 0.1.35
Unraid Docker Container: https://registry.hub.docker.com/r/homeassistant/home-assistant/

This integration used to work. Now I get this error:

``` 
2023-07-18 10:55:00.639 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Google Wifi for googlewifi
Traceback (most recent call last):
  File "/config/custom_components/googlewifi/__init__.py", line 61, in async_setup_entry
    await api.connect()
  File "/usr/local/lib/python3.11/site-packages/googlewifi/__init__.py", line 171, in connect
    success = await self.get_api_token()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/googlewifi/__init__.py", line 151, in get_api_token
    raise ConnectionError("Authorization Error")
ConnectionError: Authorization Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/googlewifi/__init__.py", line 64, in async_setup_entry
    raise PlatformNotReady from error
homeassistant.exceptions.PlatformNotReady: Authorization Error
```

I deleted the integration, updated HA but when I tried to re-add it, it was no longer an installable option within HACS (No Download button when opened within Integrations list)

**Comment by ollie4452** [comment]
I have the same issue and have not been able to fix it either.

**Comment by marc3k18** [comment]
@djtimca are tou going to be able to fix this?
